name: Functional Tests Backend
description: Run Functional Tests Backend
runs:
  using: "composite"
  steps:
    - name: Run functional test backend
      shell: bash
      run: |
        npm ci
        export CI=true
        docker compose up -d
        bash ./.github/actions/functional-test-backend/wait-kuzzle.sh
        npm run test:functional
