name: Functional Tests Backend
description: Run Functional Tests Backend
runs:
  using: "composite"
  steps:
    - name: Run functional test backend
      shell: bash
      run: |
        set +e
        docker compose run --rm api npm install
        docker compose up -d
        bash ./.github/actions/functional-test-backend/wait-kuzzle.sh
        docker compose exec api npm run test:functional
        exitcode="$?"
        [[ "$exitcode" == "0" ]] || docker compose logs api
        exit "$exitcode"
