name: Functional Tests Backend
description: Run Functional Tests Backend
runs:
  using: "composite"
  steps:
    - name: Run functional test backend
      shell: bash
      run: |
        npm install
        npx kourou app:start-services
        npm run dev &
        bash ./.github/actions/functional-test-backend/wait-kuzzle.sh
        npm run test:functional
