name: Functional Tests Backend
description: Run Functional Tests Backend
runs:
  using: "composite"
  steps:
    - name: Run functional test backend
      shell: bash
      run: |
        set +e
        docker compose run --rm --no-deps kuzzle npm install
        docker compose up -d
        bash ./.github/actions/test-functional/wait-kuzzle.sh
        docker compose exec kuzzle npm run test:functional
        exitcode="$?"
        [[ "$exitcode" == "0" ]] || docker compose logs kuzzle
        exit "$exitcode"
