name: Backend - Functional Tests
description: Run Functional Tests for backend

runs:
  using: "composite"
  steps:
    - name: Run backend functional test
      shell: bash
      run: |
        cd backend
        npm ci
        npm run build
        DOCKER_COMMAND="node app.js" docker-compose up -d
        bash features/wait-kuzzle.sh
        npm run test:functional
