version: "3"

services:
  kuzzle:
    image: kuzzleio/kuzzle-runner:16
    command: ${DOCKER_COMMAND:-npm run dev}
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    volumes:
      - .:/var/app
      - ~/.npmrc:/root/.npmrc
      - ./environments/local/kuzzlerc:/etc/kuzzlerc
    ports:
      - "7512:7512"
      - "9229:9229"
      - "1883:1883"
    depends_on:
      - redis
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__storageEngine__commonMapping__dynamic=true
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-none}
      # Uncomment when using a vault file
      # - KUZZLE_VAULT_KEY
      # - KUZZLE_SECRETS_FILE=./environments/local/secrets.enc.json

  redis:
    image: redis:5

  elasticsearch:
    image: kuzzleio/elasticsearch:7
    environment:
      - ingest.geoip.downloader.enabled=false
    ulimits:
      nofile: 65536
