name: Deploy Main Environment

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "16"
  KUZZLE_PAAS_REGISTRY: harbor.paas.kuzzle.io
  KUZZLE_PAAS_PROJECT: <PROJECT_ID>

jobs:
  push_backend:
    name: Backend artefact
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Get current commit short SHA
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=ref::$(echo $GITHUB_REF | cut -d / -f 3)"
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.KUZZLE_PAAS_REGISTRY }}
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
      - name: Login PaaS
        uses: kuzzleio/paas-action@v0.7.0
        with:
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
          npmrc_output_dir: ./apps/api
          login_only: true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./apps/api/Dockerfile
          context: ./apps/api
          push: true
          build-args: |
            KUZZLE_VAULT_KEY=${{ secrets.KUZZLE_VAULT_KEY }}
            KUZZLE_ENV=main
          tags: ${{ env.KUZZLE_PAAS_REGISTRY }}/${{ env.KUZZLE_PAAS_PROJECT }}/${{ steps.vars.outputs.ref }}/kuzzle:${{ steps.vars.outputs.sha_short }}

  deploy_backend:
    name: Deploy backend artefact
    runs-on: ubuntu-18.04
    needs: [push_backend]
    steps:
      - uses: actions/checkout@v2
      - name: Get current commit short SHA
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=ref::$(echo $GITHUB_REF | cut -d / -f 3)"
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Deploy to PaaS
        uses: kuzzleio/paas-action@v0.7.0
        with:
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
          project: ${{ env.KUZZLE_PAAS_PROJECT }}
          environment: ${{ steps.vars.outputs.ref }}
          application: api
          rollback: true
          timeout: 180 # Higher timeout for the first deployment
          image: ${{ env.KUZZLE_PAAS_REGISTRY }}/${{ env.KUZZLE_PAAS_PROJECT }}/${{ steps.vars.outputs.ref }}/kuzzle:${{ steps.vars.outputs.sha_short }}

  push_iot_console:
    name: IoT Console artefact
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Get current commit short SHA
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=ref::$(echo $GITHUB_REF | cut -d / -f 3)"
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.KUZZLE_PAAS_REGISTRY }}
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Login PaaS
        uses: kuzzleio/paas-action@v0.7.0
        with:
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
          npmrc_output_dir: ./apps/web
          login_only: true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VUE_APP_BACKEND=${{ steps.vars.outputs.ref }}
          file: ./apps/web/Dockerfile
          context: ./apps/web
          push: true
          tags: ${{ env.KUZZLE_PAAS_REGISTRY }}/${{ env.KUZZLE_PAAS_PROJECT }}/${{ steps.vars.outputs.ref }}/iot:${{ steps.vars.outputs.sha_short }}

  deploy_iot_console:
    name: Deploy IoT Console App to server
    runs-on: ubuntu-22.04
    needs: [push_iot_console]
    steps:
      - uses: actions/checkout@v2
      - name: Get current commit short SHA
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=ref::$(echo $GITHUB_REF | cut -d / -f 3)"
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Deploy to PaaS
        uses: kuzzleio/paas-action@v0.7.0
        with:
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
          project: ${{ env.KUZZLE_PAAS_PROJECT }}
          environment: ${{ steps.vars.outputs.ref }}
          application: iot
          rollback: true
          timeout: 90
          image: ${{ env.KUZZLE_PAAS_REGISTRY }}/${{ env.KUZZLE_PAAS_PROJECT }}/${{ steps.vars.outputs.ref }}/iot:${{ steps.vars.outputs.sha_short }}