name: Run functional tests and lint on development branches and pull requests

on:
  pull_request: # All pull requests

env:
  NODE_VERSION: '22'

jobs:
  test_lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Login to PaaS NPM registry
        uses: kuzzleio/paas-action@v1.2.2
        with:
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
          login_only: true
          npmrc_output_dir: .

      - name: Lint the app
        uses: ./.github/actions/test-lint

  test_functional:
    name: Functional Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Login to PaaS NPM registry
        uses: kuzzleio/paas-action@v1.2.2
        with:
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
          login_only: true
          npmrc_output_dir: .

      - name: Functionnal tests
        uses: ./.github/actions/test-functional

  test_build:
    name: Build apps
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install additional libraries
        uses: ./.github/actions/install-packages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Login to PaaS NPM registry
        uses: kuzzleio/paas-action@v1.2.2
        with:
          username: ${{ secrets.KUZZLE_PAAS_USERNAME }}
          password: ${{ secrets.KUZZLE_PAAS_PASSWORD }}
          login_only: true
          npmrc_output_dir: .

      - run: npm ci
      - run: npm run build
