name: Publish release

# on:
#   release:
#     types: [created]
on:
  push:
    branches:
      - master
jobs:
  publish-github-npm:
    name: Deploy package to the Github NPM registry
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Login to PaaS NPM registry
        uses: kuzzleio/paas-action@v0.5.7
        with:
          username: ${{ secrets.CORE_TEAM_PAAS_USERNAME }}
          password: ${{ secrets.CORE_TEAM_PAAS_PASSWORD }}
          login_only: true

      - name: Install dependencies
        run: |
          npm install

      - name: Set Github package registry
        run: |
          npm config set @kuzzleio:registry https://npm.pkg.github.com -L project
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GPR_TOKEN }} -L project

      - name: Build & Publish package
        run: |
          npx turbo build
          npx turbo publish-packages

