name: Push to master

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: "16"

      - name: Login to PaaS NPM registry
        uses: kuzzleio/paas-action@v0.5.7
        with:
          username: ${{ secrets.CORE_TEAM_PAAS_USERNAME }}
          password: ${{ secrets.CORE_TEAM_PAAS_PASSWORD }}
          login_only: true
          npmrc_output_dir: ./

      - name: Copy NPMRC
        run: cp .npmrc ~/.npmrc

      - uses: ./.github/actions/lint

  functional-tests-backend:
    name: Functional Tests
    runs-on: ubuntu-22.04
    needs: [lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: "16"

      - name: Login to PaaS NPM registry
        uses: kuzzleio/paas-action@v0.5.7
        with:
          username: ${{ secrets.CORE_TEAM_PAAS_USERNAME }}
          password: ${{ secrets.CORE_TEAM_PAAS_PASSWORD }}
          login_only: true
          npmrc_output_dir: ./

      - name: Copy NPMRC
        run: cp .npmrc ~/.npmrc

      - uses: ./.github/actions/functional-test-backend
